### ISSUE TITLE
Incompatibility error with 1.6.0

### ISSUE THREAD

**Issue by Anvil5465** [Armitxes/StardewValley_UnlimitedPlayers#21] opened 2024-03-20 14:45 UTC
SMAPI gave me an error with the new update saying that the unlimited players mod is not compatible with 1.6.0

**Comment by Armitxes** [comment] 2024-03-30 16:41
Thanks for the report. The issue is resolved with the latest release v2024.03.30 
#23

**Closed as completed by Armitxes** 2024-03-30 16:41 UTC
Labels: Fixed
