### ISSUE TITLE
After update 1.4 players get stuck

### ISSUE THREAD

**Issue by NattieDK** [Armitxes/StardewValley_UnlimitedPlayers#12] opened 2019-11-27 13:19 UTC
When more then 4 players enter the game, the new players get stuck i top left coner of the home building, and cannot move. When one og the four goes offline the new player can enter. But gets to share the host postbox and bed. Even though we have build a new carbin. ? what to do? Just found out its ONLY on the new map the problem is

**Comment by Rhyagelle** [comment] 2019-11-30 00:07
Any idea if this is going to be patched for 1.4? 

EDIT

I was able to play with 4+ people if we didn't select Four Corners map as stated above. :)

**Comment by scd31** [comment] 2020-02-01 22:44
I was unable to reproduce this. There were 5 of us playing the four corners map for about 6 hours. We didn't run into any issues so this can probably be closed.

**Comment by Armitxes** [comment] 2020-02-02 12:15
Alright closing this issue. Unable 2 reproduce myself. Yet there will be a stability patch heading out soon.

**Closed as completed by Armitxes** 2020-02-02 12:15 UTC
